name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Gradle Wrapper (if missing)
        run: |
          if [ ! -f gradlew ]; then
            curl -sL https://services.gradle.org/distributions/gradle-8.10-bin.zip -o gradle.zip
            unzip -q gradle.zip
            mv gradle-8.10/bin/gradlew .
            chmod +x gradlew
            rm -rf gradle.zip gradle-8.10
          else
            chmod +x gradlew
          fi

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk